---
- name: Add Elastic GPG Key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elastic {{ elasticsearch_version }} repository
  apt_repository:
    repo: "{{ elasic_repo }}/{{ elasticsearch_version }}/apt stable main"
    state: present
    update_cache: true

- name: Stop filebeat
  service:
    name: filebeat
    state: stopped
  ignore_errors: true

- name: Install Filebeat
  apt:
    name: "filebeat={{ release_version }}"
  notify:
    - Stop filebeat

- name: Create filebeat configs directory
  file:
    path: '/etc/filebeat/configs'
    state: directory
    mode: 0755

- name: Add filebeat configuration file
  template:
    src: 'etc/filebeat/filebeat.yml.tpl'
    dest: '/etc/filebeat/filebeat.yml'

- name: Change logging configuration
  lineinfile:
    path: "{{ item.path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { path: '{{ filebeat_daemon_file }}', regexp: '^Environment="BEAT_LOG', line: '#Environment="BEAT_LOG_OPTS=-e"' }
    - { path: '{{ filebeat_daemon_file }}', regexp: '^ExecStart=', line: 'ExecStart=/usr/share/filebeat/bin/filebeat $BEAT_CONFIG_OPTS $BEAT_PATH_OPTS' }

- name: Add configuration files
  template:
    src: 'etc/filebeat/configs/{{ item }}.tpl'
    dest: '/etc/filebeat/configs/{{ item }}'
  loop:
    - laravel.yml
    - nginx.yml
    - socket.yml
    - syslog.yml
    - horizon.yml
    - sns.yml
    - php.yml

- name: Create crt directory
  file:
    path: '/etc/filebeat/ssl'
    state: directory
    mode: 0755

- name: Add certificate
  copy:
    src: '{{ crt_file_src }}'
    dest: '/etc/filebeat/ssl/logstash.crt'
  notify:
    - Restart filebeat

- name: Add configuration files
  template:
    src: 'etc/filebeat/configs/{{ item }}.tpl'
    dest: '/usr/share/filebeat/configs/{{ item }}'
  loop:
    - laravel.yml
    - nginx.yml
    - socket.yml
    - syslog.yml
    - horizon.yml
    - sns.yml
    - php.yml
  when: ansible_distribution == "Alpine"

- name: Create crt directory
  file:
    path: '/usr/share/filebeat/ssl'
    state: directory
    mode: 0755
  when: ansible_distribution == "Alpine"

- name: Add certificate
  copy:
    src: '{{ crt_file_src }}'
    dest: '/usr/share/filebeat/ssl/logstash.crt'
  when: ansible_distribution == "Alpine"
