---
  - name: Add Elastic GPG Key
    apt_key:
      url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      state: present
  - name: Add Elastic repository
    apt_repository:
      repo: "deb https://artifacts.elastic.co/packages/{{ elasticsearch_version }}/apt stable main"
      state: present
      update_cache: yes
  - name: Install Filebeat
    apt:
      name: filebeat
  - name: Add confiration files
    copy:
      src: 'files/etc/'
      dest: '/etc/'
  - name: Add confiration files
    template:
      src: 'files/etc/filebeat/filebeat.yml'
      dest: '/etc/filebeat/filebeat.yml'
  - name: Create crt directory
    file:
      path: '/etc/filebeat/ssl'
      state: directory
      mode: 0755
  - name: Add certificate
    copy:
      src: '{{ crt_file_src }}'
      dest: '/etc/filebeat/ssl/logstash.crt'
  - name: Restart filebeat
    service:
      name: filebeat
      state: restarted
