---
- name: Install packages
  apk:
    name:
      - tar
      - libc6-compat
    update_cache: true
  tags:
    - packages

- name: Download filebeat
  get_url:
    url: "https://artifacts.elastic.co/downloads/\
    beats/filebeat/filebeat-{{ release_version }}-linux-x86_64.tar.gz"
    dest: '/tmp/filebeat-{{ release_version }}-linux-x86_64.tar.gz'
    mode: '0644'
  tags:
    - packages

- name: Install filebeat
  unarchive:
    src: '/tmp/filebeat-{{ release_version }}-linux-x86_64.tar.gz'
    dest: '/usr/share'
    extra_opts:
      - --transform
      - 's/filebeat-{{ release_version }}-linux-x86_64/filebeat/'
  tags:
    - packages

- name: Delete filebeat archive installer
  file:
    path: '/tmp/filebeat-{{ release_version }}-linux-x86_64.tar.gz'
    state: absent
  tags:
    - packages

- name: Create filebeat configs directory
  file:
    path: '/usr/share/filebeat/configs'
    state: directory
    mode: 0755
  tags:
    - configuration

- name: Add filebeat configuration file
  template:
    src: 'etc/filebeat/filebeat.yml.tpl'
    dest: '/usr/share/filebeat/filebeat.yml'
    mode: 0600
  tags:
    - configuration

- name: Add configuration files
  template:
    src: 'etc/filebeat/configs/{{ item }}.tpl'
    dest: '/usr/share/filebeat/configs/{{ item }}'
    mode: 0644
  loop:
    - laravel.yml
    - nginx.yml
    - socket.yml
    - syslog.yml
    - horizon.yml
    - sns.yml
    - php.yml
    - gss.yml
  tags:
    - configuration

- name: Create crt directory
  file:
    path: '/usr/share/filebeat/ssl'
    state: directory
    mode: 0755
  tags:
    - configuration

- name: Add certificate
  copy:
    src: '{{ crt_file_src }}'
    dest: '/usr/share/filebeat/ssl/logstash.crt'
    mode: 0644
  tags:
    - configuration
