---
- name: Install gnu-tar
  apk:
    name: tar
    update_cache: yes

- name: Download filebeat
  get_url:
    url: 'https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ release_version }}-linux-x86_64.tar.gz'
    dest: '/tmp/filebeat-{{ release_version }}-linux-x86_64.tar.gz'
    mode: '0644'

- name: Install filebeat
  unarchive:
    src: '/tmp/filebeat-{{ release_version }}-linux-x86_64.tar.gz'
    dest: '/usr/share'
    extra_opts:
    - --transform
    - 's/filebeat-{{ release_version }}-linux-x86_64/filebeat/'

- name: Create filebeat configs directory
  file:
    path: '/usr/share/filebeat/configs'
    state: directory
    mode: 0755

- name: Add filebeat configuration file
  template:
    src: 'etc/filebeat/filebeat.yml.tpl'
    dest: '/usr/share/filebeat/filebeat.yml'

- name: Add configuration files
  template:
    src: 'etc/filebeat/configs/{{ item }}.tpl'
    dest: '/usr/share/filebeat/configs/{{ item }}'
  loop:
    - laravel.yml
    - nginx.yml
    - socket.yml
    - syslog.yml
    - horizon.yml
    - sns.yml
    - php.yml

- name: Create crt directory
  file:
    path: '/usr/share/filebeat/ssl'
    state: directory
    mode: 0755

- name: Add certificate
  copy:
    src: '{{ crt_file_src }}'
    dest: '/usr/share/filebeat/ssl/logstash.crt'
