---
- name: Add filebeat repository
  lineinfile:
    path: /etc/apk/repositories
    line: http://dl-cdn.alpinelinux.org/alpine/edge/testing

- name: Install filebeat
  apk:
    name: "filebeat={{ release_version }}-r0"
    update_cache: yes

- name: Create filebeat configs directory
  file:
    path: '/usr/share/filebeat/configs'
    state: directory
    mode: 0755

- name: Add filebeat configuration file
  template:
    src: 'etc/filebeat/filebeat.yml.tpl'
    dest: '/usr/share/filebeat/filebeat.yml'

- name: Add configuration files
  template:
    src: 'etc/filebeat/configs/{{ item }}.tpl'
    dest: '/usr/share/filebeat/configs/{{ item }}'
  loop:
    - laravel.yml
    - nginx.yml
    - socket.yml
    - syslog.yml
    - horizon.yml
    - sns.yml
    - php.yml

- name: Create crt directory
  file:
    path: '/usr/share/filebeat/ssl'
    state: directory
    mode: 0755

- name: Add certificate
  copy:
    src: '{{ crt_file_src }}'
    dest: '/usr/share/filebeat/ssl/logstash.crt'
