---
- import_tasks: setup-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- import_tasks: setup-debian.yml
  when: ansible_distribution == 'Debian'

- import_tasks: setup-alpine.yml
  when: ansible_distribution == 'Alpine'
