---

- name: Stop filebeat
  service:
    name: filebeat
    state: stopped

- name: Start filebeat
  service:
    name: filebeat
    state: started

- name: Restart filebeat
  service:
    name: filebeat
    state: restarted
