---

- name: Stop filebeat
  service:
    name: filebeat
    state: stopped

- name: Start filebeat
  service:
    name: filebeat
    state: started
    enabled: true

- name: Restart filebeat
  service:
    name: filebeat
    state: restarted
    daemon_reload: true
